name: Phoenix Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Start Bot
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
        run: npm start
